# Лимиты на первый проект TTS
MAX_SYMBOLS = 10000
MAX_USERS = 8
MAX_SYMBOLS_FOR_USER = MAX_SYMBOLS // MAX_USERS
MAX_SYMBOLS_IN_MESSAGE = 250

# Лимиты на второй проект STT
MAX_BLOCKS = 64
MAX_BLOCKS_FOR_USER = MAX_BLOCKS // MAX_USERS
SECONDS_IN_BLOCK = 15
MAX_BLOCKS_IN_MESSAGE = 2
